// mockData.js

export const MockData = [
    {
      id: 1,
      name: 'Bateta Pauva',
      image: require("../../assets/FoodItems/BatetaPuva.png"), // or a remote URL
      owner: 'Paul Roberto',
      rating: 4.1,
      area: 'Dublin',
      price: 2.99,
      isVeg: true,
      cookedOn: '2025-02-26 09:15 AM',
      description: 'Flattened rice cooked with spiced potatoes, curry leaves, and mustard seeds.',
    },
    {
      id: 2,
      name: 'Chicken Tikka Masala',
      image: require("../../assets/FoodItems/ChickenTikka.png"),
      owner: 'Osama Khan',
      rating: 4.8,
      area: 'Manchester',
      price: 7.49,
      isVeg: false,
      cookedOn: '2025-02-26 01:00 PM',
      description: 'Tender chicken pieces in a rich, creamy tomato-based sauce.',
    },
    {
      id: 3,
      name: 'Crab Gaon Style',
      image: require("../../assets/FoodItems/Crab-Masala Goan Style.png"),
      owner: 'Fernandes Agillio',
      rating: 4.6,
      area: 'Harrow on the Hill',
      price: 12.99,
      isVeg: false,
      cookedOn: '2025-02-25 07:45 PM',
      description: 'Whole crab cooked in a spicy coconut masala, typical of coastal regions.',
    },
    {
      id: 4,
      name: 'Ghughra',
      image: require("../../assets/FoodItems/Ghughra.png"),
      owner: 'Nandan Maheta',
      rating: 4.2,
      area: 'Leads',
      price: 3.49,
      isVeg: true,
      cookedOn: '2025-02-26 08:00 AM',
      description: 'Sweet dumplings stuffed with coconut, dry fruits, and cardamom.',
    },
    {
      id: 5,
      name: 'Girnari Khichdi',
      image: require("../../assets/FoodItems/GiranriKhichdi.png"),
      owner: 'Clinton BossMan',
      rating: 4.9,
      area: 'Central London',
      price: 4.99,
      isVeg: true,
      cookedOn: '2025-02-26 12:30 PM',
      description: 'Hearty Gujarati khichdi with rice, lentils, and vegetables cooked in ghee.',
    },
    {
      id: 6,
      name: 'Hamburger',
      image: require("../../assets/FoodItems/HamBurger.png"),
      owner: 'Miller Patel',
      rating: 4.4,
      area: 'Central Dublin',
      price: 5.99,
      isVeg: false,
      cookedOn: '2025-02-26 06:00 PM',
      description: 'Juicy beef patty with cheese, lettuce, tomato, onions, and special sauce.',
    },
    {
      id: 7,
      name: 'Masala Kabab',
      image: require("../../assets/FoodItems/Kabab.png"),
      owner: 'Ansari al Maqsooni',
      rating: 4.7,
      area: 'Wembley',
      price: 6.49,
      isVeg: false,
      cookedOn: '2025-02-25 07:00 PM',
      description: 'Spiced kebabs grilled to perfection, served with green chutney and onions.',
    },
    {
      id: 8,
      name: 'Rotlo-Oro',
      image: require("../../assets/FoodItems/Oro-Rotlo.png"),
      owner: 'AnirudhSinh Gohil',
      rating: 4.1,
      area: 'Heathrow Area Greater London',
      price: 3.99,
      isVeg: true,
      cookedOn: '2025-02-26 11:45 AM',
      description: 'Rustic millet flatbread served with smoky mashed brinjal (oro).',
    },
    {
      id: 9,
      name: 'Pizza',
      image: require("../../assets/FoodItems/Pizza.png"),
      owner: 'Rossi di Capaciyo',
      rating: 4.8,
      area: 'Naples',
      price: 8.99,
      isVeg: false, 
      cookedOn: '2025-02-25 08:15 PM',
      description: 'Classic pizza with tomato sauce, cheese, pepperoni, olives, and fresh basil.',
    },
  ];
  